[package]
name = "hookevent_lib"
version = "1.0.0"
edition = "2024"
description="Hook event System from GLua on Rust library"
repository="github.com/Neonpk/hookevent_lib"
keywords = ["Events", "Hooks", "Handlers"]

[dependencies]
once_cell = "1.20.3"